---
title: Klimpiek
author: Robert Guiscard
email: hello@klimpiek.com
description: Klimpiek is a productivity tools capable of note-keeping, bookmarking
  and todo list
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
